const workersList = [
  { name: "John1", surname: 'Smith', salary: 500 },
  { name: "John2", surname: 'Smith', salary: 500 },
  { name: "John3", surname: 'Smith', salary: 500 },
  { name: "John4", surname: 'Smith', salary: 500 },
  { name: "John5", surname: 'Smith', salary: 500 },
  { name: "John6", surname: 'Smith', salary: 500 },
  { name: "John7", surname: 'Smith', salary: 500 },
  { name: "John8", surname: 'Smith', salary: 500 },
  { name: "John9", surname: 'Smith', salary: 500 },
  { name: "John10", surname: 'Smith', salary: 500 },
  { name: "John11", surname: 'Smith', salary: 500 },
  { name: "John12", surname: 'Smith', salary: 500 },
  { name: "John13", surname: 'Smith', salary: 500 },
  { name: "John14", surname: 'Smith', salary: 500 },
  { name: "John15", surname: 'Smith', salary: 500 },
  { name: "John16", surname: 'Smith', salary: 500 },
  { name: "John17", surname: 'Smith', salary: 500 },
  { name: "John18", surname: 'Smith', salary: 500 },
  { name: "John19", surname: 'Smith', salary: 500 },
  { name: "John20", surname: 'Smith', salary: 500 },
  { name: "John21", surname: 'Smith', salary: 500 },
  { name: "John22", surname: 'Smith', salary: 500 },
  { name: "John23", surname: 'Smith', salary: 500 },
  { name: "John24", surname: 'Smith', salary: 500 },
  { name: "John25", surname: 'Smith', salary: 500 },
];

export default workersList;
